### ISSUE TITLE
Update device list to support CoreOS 2.0

### ISSUE THREAD

**Issue by kamui** [Vheissu/cortex-device-list#2]
NeuralDSP updated the Quad Cortex firmware to 2.0.0, adding a few amps, new overdrive, and hundreds of captures. Would be cool to update the device list to support the additions, new PDF doc is here:

https://downloads.neuraldsp.com/file/quad-cortex/Quad+Cortex+User+Manual+2_0_0.pdf

**Comment by Vheissu** [comment]
On the case @kamui thank you for creating an issue for this.

**Comment by Vheissu** [comment]
All done :)

**Comment by kamui** [comment]
Thank you!
